language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"

install:
    - pip install pep8 --use-mirrors

script:
    - pep8 *.py --ignore E501
    - python msparser_test.py --verbose

notifications:
  email:
    - turcotte.mat@gmail.com

