language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"

install:
    - pip install unittest2 --use-mirrors
    - pip install pep8 --use-mirrors
    - pip install coverage --use-mirrors

script:
    - pep8 *.py --ignore E501
    - coverage run --omit *test.py msparser_test.py --verbose
    - coverage report -m

notifications:
  email:
    - turcotte.mat@gmail.com

